version: "3.9"
services:
  myapp:
    build: .
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=postgresql://postgres:lZUoJCRONEbeflwiIAUPbeYCFdxxCnKa@<PUBLIC-HOSTNAME>:5432/railway


